modLoader = "javafml" #mandatory
loaderVersion = "[46,47,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license = "GNU LGPL 3.0"
issueTrackerURL = "https://jp3/infusion_table/issues"

[[mods]] #mandatory
modId = "infusion_table" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
#updateJSONURL="http://myurl.me/" #optional
#displayURL="http://example.com/" #optional
logoFile = "icon.png" #optional
authors="${mod_authors}"
description = '''${mod_description}'''

[[dependencies.infusion_table]]
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[46,47,)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.infusion_table]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.infusion_table]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"
