# Dev
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
#org.gradle.caching=false
#org.gradle.caching.debug=false
#org.gradle.configureondemand=false

# Minecraft
minecraft_version=1.21.2
enabled_platforms=fabric,neoforge

# Mod
archives_name=infusion_table
maven_group=xyz.jptrzy

mod_name=Infusion Table
mod_version=1.2.2+1.21.2
mod_authors=jptrzy
mod_description=It introduces the possibility of disenchanting items for enchanted books.

# Dependencies
## https://generate.architectury.dev
architectury_api_version=14.0.4

## Fabric
## https://fabricmc.net/develop/
yarn_mappings=1.21.2+build.1
fabric_loader_version = 0.19.5
fabric_api_version = 0.106.1+1.21.2

fabric_fabric_version=>=0.106.1+1.21.2
fabric_architectury_version=>=14.0.4
fabric_minecraft_version=>=1.21.2

## Neoforge
neoforge_version = 21.2.1-beta

neoforge_loader_version = [4,)
neoforge_neoforge_version = [21.2,)
neoforge_minecraft_version = [1.21.2,)
neoforge_architectury_version = [14.0.4,)
yarn_mappings_patch_neoforge_version = 1.21+build.6
