# Dev
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
#org.gradle.caching=false
#org.gradle.caching.debug=false
#org.gradle.configureondemand=false

# Minecraft
minecraft_version=1.20.5
enabled_platforms=fabric,neoforge

# Mod
archives_name=infusion_table
maven_group=xyz.jptrzy

mod_name=Infusion Table
mod_version=1.2.1+1.20.5
mod_authors=jptrzy
mod_description=Adds a possibility for disenchanting items for enchanted books

# Dependencies
## https://generate.architectury.dev
architectury_api_version=12.0.29

## Fabric
## https://fabricmc.net/develop/
yarn_mappings=1.20.5+build.1
fabric_loader_version=0.19.3
fabric_api_version=0.97.8+1.20.5

fabric_architectury_version=>=12.0.29
fabric_minecraft_version=>=1.20.5

## Neoforge
neoforge_version = 20.5.21-beta

neoforge_loader_version = [2,)
neoforge_neoforge_version = [20.5,)
neoforge_minecraft_version = [1.20.5,)
neoforge_architectury_version = [12.0.29,)
yarn_mappings_patch_neoforge_version = 1.20.5+build.3
